# Generated by Django 5.0.4 on 2024-04-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
