# Generated by Django 5.0.4 on 2024-05-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classes_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='plains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('startTime', models.TimeField(auto_now=True)),
                ('endTime', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='classes',
            name='date',
            field=models.TimeField(),
        ),
    ]
