# Generated by Django 5.0.4 on 2024-05-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_plains_alter_classes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plains',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plains',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
