# Generated by Django 5.0.4 on 2024-05-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_classes_classend_alter_classes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='image',
            field=models.FileField(default=None, upload_to='class/'),
        ),
    ]
