# Generated by Django 5.0.4 on 2024-05-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_classes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plains',
            name='image',
            field=models.FileField(default=None, upload_to='plains/'),
        ),
    ]
