# Generated by Django 5.0.4 on 2024-05-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contactNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='endDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='client',
            name='startDate',
            field=models.DateField(default=None),
        ),
    ]
