# Generated by Django 5.0.4 on 2024-05-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_clientstatus_client_contactnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='endDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='startDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
